name: Build repo

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get docker image and compile face
        run: |
          docker run --rm                          \
            "--volume=`pwd`:/project"              \
            --workdir /project                     \
            ddls/esp32_platformio_compiler:latest  \
            /bin/bash -c                           \
            "pio run -e release"
      - name: Upload face binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: Watchy-Screen-Face
          path: .pio/build/release/firmware.bin